CREATE TABLE IF NOT EXISTS shop.orders
(
    id UUID PRIMARY KEY,
    product_id UUID REFERENCES shop.products (id) ON UPDATE CASCADE ON DELETE SET NULL,
    user_id UUID REFERENCES shop.users (id) ON UPDATE CASCADE ON DELETE SET NULL
)